name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      CI: false

    steps:
    - uses: actions/checkout@v4

    - name: Run
      run: make
